lsi: false
safe: true
source: main
incremental: false
highlighter: rouge
gist:
  noscript: false
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-minimal
gitalk:
  clientID: 'Ov23liUB3zvAkXmUoWSa'
  clientSecret: 'ded08e1806895fafba41a2f9035170d3c81afecc'
  repo: 'comments'
  owner: 'CB-X2-Jun'
  admin: ['CB-X2-Jun']
  distractionFreeMode: false
